    
runtime: php74
env: standard
instance_class: F1

runtime_config:
    
    document_root: public #folder where index.php is

handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$



- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
 # Put production environment variables here.
 APP_LOG: errorlog
 APP_ENV: local   # or production
 APP_DEBUG : true # or false 
 APP_KEY: base64:JAGFLvx9AX/K64y0FaODCsTum/3ikmyBg1SK5LRcAaU=
 APP_STORAGE: /tmp
 VIEW_COMPILED_PATH: /tmp
 CACHE_DRIVER: database
 SESSION_DRIVER: cookie
 
# follow the part of the tutorial on setting up your SQL database
 DB_CONNECTION: mysql
 DB_HOST: localhost
 DB_PORT: 3306
 DB_DATABASE: epicdevdb
 DB_USERNAME: epicdbdevuser
 DB_PASSWORD: epicdbdevuser
 DB_SOCKET: "/cloudsql/epicportal:us-central1:epicportaldb"  #here need instance from cloudsql

 #GOOGLE_VISION_PROJECT_ID : epicportal

#we need this for the flex environment
beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: "epicportal:us-central1:epicportaldb"
