steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - cp
    - .env.testing
    - .env
- name: 'docker/compose:1.23.1'
  args:
    - run
    - app
    - composer
    - install
    - --optimize-autoloader
    - --no-interaction
    - --no-ansi
    - --no-progress
    - --no-scripts
    - --prefer-dist
- name: 'docker/compose:1.23.1'
  args:
    - run
    - app
    - vendor/bin/phpunit
    - --no-coverage
- name: 'gcr.io/epicportal/docker'
  args:
    - cp
    - ${_APP_YAML_CONFIG}
    - app.yaml
- name: 'gcr.io/epicportal/docker'
  args:
    - app
    - deploy
    - --no-promote
timeout: '600s'
